### ISSUE TITLE
ERROR in src/app/main/main.component.ts(17,25): error TS2307: Cannot find module 'SubSink'.

### ISSUE THREAD

**Issue by manuabhijit** [wardbell/subsink#4]
I am using **sub sink** for a while now in all my Angular Projects. 
It works well on my local machine (Windows)

Now while trying it on Code Pipeline it started giving me errors.

```
image: node:10.15.0
pipelines:
  branches:
    master:
      - step:
          deployment: test
          script:
            - npm i typescript serverless subsink -g
            - npm i
            - npm i subsink --save
            - serverless config credentials --overwrite --provider aws --key xxx --secret xxx
            - npm run build:prod:deploy
```

Nothing was available on the stack overflow as well.
